# Generated by Django 2.2.7 on 2019-12-27 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ojuser',
            name='cf_handle',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
