# Generated by Django 2.0.1 on 2018-03-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='handle',
            field=models.CharField(error_messages={'unique': '账号已存在'}, help_text='<ul><li>必填</li></ul>', max_length=20, unique=True, verbose_name='CF账号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='realname',
            field=models.CharField(error_messages={'blank': '不能为空'}, help_text='<ul><li>必填</li></ul>', max_length=10, verbose_name='真名'),
        ),
    ]
