# Generated by Django 2.2 on 2019-12-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0002_auto_20180308_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Captcha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('handle', models.CharField(max_length=20, unique=True)),
                ('update_time', models.DateTimeField()),
                ('captcha', models.CharField(max_length=200)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
