# Generated by Django 2.2.7 on 2019-12-13 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0004_auto_20191211_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='oj_password',
        ),
    ]
