# Generated by Django 2.2.7 on 2019-12-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0005_remove_user_oj_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='handle',
            field=models.CharField(max_length=20),
        ),
    ]
