# Generated by Django 2.0.1 on 2018-01-31 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CFUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=30, unique=True)),
                ('rating', models.IntegerField(default=0)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('realname', models.CharField(default='', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='RatingChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_ago', models.IntegerField()),
                ('oldRating', models.IntegerField(default=0)),
                ('newRating', models.IntegerField(default=0)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('cf_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.CFUser')),
            ],
        ),
    ]
