# Generated by Django 2.0.1 on 2018-04-29 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='effective_time',
        ),
    ]
