# Generated by Django 2.0.1 on 2018-04-29 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_remove_board_effective_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boarditem',
            old_name='oldRating',
            new_name='old_rating',
        ),
    ]
