# Generated by Django 2.0.1 on 2018-04-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20180429_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingchange',
            name='days_ago',
        ),
        migrations.AlterField(
            model_name='ratingchange',
            name='ratingUpdateTimeSeconds',
            field=models.IntegerField(),
        ),
    ]
